import { ref, computed } from 'vue'

// 表格字段
export const tableColumnsConfig = ref([
    {
        title: '操作',
        key: 'action',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 200,
        fixed: 'left',
    },
    {
        title: '用户ID',
        dataIndex: 'user_id',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 100,
        sorter: true,
        fixed: "left",
    },
    {
        title: '名称',
        dataIndex: 'name',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 120,
    },
    {
        title: '账号',
        dataIndex: 'account',
		visible: true,
        align: 'center',
        width: 100,
    },
    {
        title: '头像',
        dataIndex: 'avatar',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 50,
    },
    {
        title: '生日',
        dataIndex: 'birthday',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 120,
        sorter: true,
    },
    {
        title: '性别',
        dataIndex: 'sex',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 100,
        sorter: true,
        filters: [{ text: '男', value: '1' }, { text: '女', value: '2' }, { text: '未知', value: '3' }],
    },
    {
        title: '角色',
        dataIndex: 'role_list',
		visible: true,
        align: 'left',
        ellipsis: true,
        width: 100,
    },
    {
        title: '手机号',
        dataIndex: 'phone',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 100,
        sorter: true,
    },
    {
        title: '电子邮箱',
        dataIndex: 'email',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 150,
        sorter: true,
    },
    {
        title: '真实姓名',
        dataIndex: 'real_name',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 80,
    },
    {
        title: '身份证号',
        dataIndex: 'idcard',
		visible: true,
        align: 'center',
        sorter: true,
        ellipsis: true,
        width: 150,
    },
    {
        title: '登录IP',
        dataIndex: 'login_ip',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 120,
        sorter: true,
    },
    {
        title: '登录时间',
        dataIndex: 'login_time',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 150,
        sorter: true,
    },
    {
        title: '禁用',
        dataIndex: 'is_disable',
		visible: true,
        align: 'center',
        ellipsis: true,
        width: 70,
        sorter: true,
        fixed: "right",
    }
])

export const tableColumns = computed(() => {
  	return tableColumnsConfig.value.filter(col => col.visible !== false)
})
